# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [1]:
import numpy as np     # importing numpy library

In [2]:
A = np.array(5)        # Scalar Array
A

array(5)

In [3]:
np.ndim(A)               # Dimension method

0

In [4]:
One = np.array([1, 2, 3, 4, 5])
Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [5]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
Three.shape

(2, 2, 3)

In [10]:
print(np.ndim(One))
print(np.ndim(Two))
print(np.ndim(Three))

1
2
3


# List vs Numpy Array

In [11]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [14]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [15]:
arr = np.array([1, 2, 3, 4, 5])             # Allows Mathematical Operations

print(arr/5)                                # Division
print(arr*5)                                # Multiplication
print(arr+5)                                # Addition
print(arr-5)                                # Subtraction

[0.2 0.4 0.6 0.8 1. ]
[ 5 10 15 20 25]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]


In [16]:
list1/5                                     #list will give Error for mathematical Operation

TypeError: unsupported operand type(s) for /: 'list' and 'int'

**More Advantages of Numpy Array over list**
*   Array consumes less memory
*   Array are faster than lists



# Reshaping arrays

Reshaping means changing the shape of an array.

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)


In [18]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# 1D to 3D Array

newarr = arr.reshape(2, 3, 2)    # x,y,z: x = matrix, y = rows, z = cols

In [20]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [21]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [22]:
print(arr[0] + arr[1])                 # Addition of 2 elements

3


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
print(arr.shape)

print(arr[0, 3])                          # 1st row 4th element
print(arr[1, 1])                          # 2nd row 5th element
print(arr[1,3])

(2, 5)
4
7
9


In [32]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

arr3.shape
print(arr3)
print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column
print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column
print(arr3[0,1,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
11
4


In [26]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
