## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [8]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7])                          # Slicing 1D Array

print(a1[1:5])     # Slicing                                  # [start:end]
print(a1[4])       # Indexing
print(a1[:4])

[2 3 4 5]
5
[1 2 3 4]


In [6]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])           # Slicing 2D Array
print(a2)

print(a2[1, 1:4])                                            # [row:column]
print(a2[0:2, 2])
print(a2[1:, :5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
[[ 6  7  8  9 10]]


In [9]:
a2.shape

(2, 5)

In [11]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])           # # Slicing 3D Array

In [12]:
print(a3)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [13]:
print(a3[:2,1:,:2])                                                         # [matrix:row:column])

[[[13 14]
  [16 17]]

 [[23 24]
  [26 27]]]


In [14]:
a3[:2,1:,:]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[23, 24, 25],
        [26, 27, 28]]])

# View vs Copy

Copy is a new array, and the View is just a view of the original array.

Any changes made to the **copy** will not affect original array.

Any changes made to the **view** will affect the original array.

In [15]:
arr = np.array([1, 2, 3, 4, 5])

# Copy Method

copy = arr.copy()
copy[0] = 42

print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [16]:
# View Method

view = arr.view()
view[0] = 42

print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


# Append , Insert and Delete Operations

In [28]:
a = np.array([[1,2,3],
              [4,5,6]])
a.shape
# Append Method

print(np.append(a, [7,8,9]))
print()
print(np.append(a, [[7,8,9]],axis = 0))               # axis = 0 = row
print()
print(np.append(a, [[5],[8]],axis = 1))               # axis = 1 = col

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 5]
 [4 5 6 8]]


In [30]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

# Insert Method

print(np.insert(a,3,[11,12]))
print()
print(np.insert(a,1,[11,12],axis = 0))
print()
print(np.insert(a,1,[11,12,13],axis = 1))

[ 1  2  3 11 12  4  5  6]

[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]

[[ 1 11  2]
 [ 3 12  4]
 [ 5 13  6]]


In [31]:
a = np.array([[ 1,  2,  3, 12],
              [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])

# Delete Method

print(np.delete(a,4))
print()
print(np.delete(a,1,axis = 1))
print()
print(np.delete(a,1,axis = 0))

[ 1  2  3 12  5  6 11  8  4 10  7]

[[ 1  3 12]
 [ 9  6 11]
 [ 8 10  7]]

[[ 1  2  3 12]
 [ 8  4 10  7]]


In [32]:
np.ndim(a)

2

# Hstack vs Vstack

Hstack is used to join two arrays **Horizontally**.

Vstack is used to join two arrays **Vertically**.


In [33]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [34]:
print(a,b)
print(np.ndim(a), np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [35]:
# Performing Hstack

result = np.hstack((a,b))

print(result)
print(np.ndim(result))

[1 2 3 4 5 6]
1


In [38]:
# Performing Vstack

result = np.vstack((a,b))

print(result)
print(np.ndim(result))

[[1 2 3]
 [4 5 6]]
2


# Numpy Concatenation

It is used for joining two or more arrays of the same shape along a specified axis.

Axis = 0, Adding new rows

Axis = 1, Adding new columns


In [44]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

print(arr1.shape,arr2.shape)
print()
arr3 = np.array([[3], [9]])
arr4 = np.array([[4] , [8]])

print(arr3.shape,arr4.shape)
print()
new = np.concatenate((arr1, arr2), axis = 0)

print(new)
print()
print(new.shape)

(2, 2) (2, 2)

(2, 1) (2, 1)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]

(4, 2)


In [46]:
new = np.concatenate((arr1, arr2), axis = 1)

print(new)

[[2 4 3 5]
 [6 8 7 9]]
